version: 2

project_name: secretscan

before:
  hooks:
    - go mod tidy
    - go vet ./...
    - go test ./...

builds:
  - main: ./cmd/secretscan
    binary: secretscan
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/secretscan/secretscan/internal/cli.version={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - .secretscan.yaml
      - .secretignore

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: Nciibi
    name: secretscan
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
